/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignTokenRouteImport } from './routes/sign.$token'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppServicesRouteImport } from './routes/_app/services'
import { Route as AppSalesRouteImport } from './routes/_app/sales'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppRankingRouteImport } from './routes/_app/ranking'
import { Route as AppInvestmentsRouteImport } from './routes/_app/investments'
import { Route as AppInsightsRouteImport } from './routes/_app/insights'
import { Route as AppGoalsRouteImport } from './routes/_app/goals'
import { Route as AppForecastRouteImport } from './routes/_app/forecast'
import { Route as AppFinancialRouteImport } from './routes/_app/financial'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCreditIntelligenceRouteImport } from './routes/_app/credit-intelligence'
import { Route as AppContractsRouteImport } from './routes/_app/contracts'
import { Route as AppCommissionsRouteImport } from './routes/_app/commissions'
import { Route as AppClientsRouteImport } from './routes/_app/clients'
import { Route as AppCashflowRouteImport } from './routes/_app/cashflow'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppBankRouteImport } from './routes/_app/bank'
import { Route as AppAlertsRouteImport } from './routes/_app/alerts'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignTokenRoute = SignTokenRouteImport.update({
  id: '/sign/$token',
  path: '/sign/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRankingRoute = AppRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestmentsRoute = AppInvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppForecastRoute = AppForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancialRoute = AppFinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCreditIntelligenceRoute = AppCreditIntelligenceRouteImport.update({
  id: '/credit-intelligence',
  path: '/credit-intelligence',
  getParentRoute: () => AppRoute,
} as any)
const AppContractsRoute = AppContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AppRoute,
} as any)
const AppCommissionsRoute = AppCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppCashflowRoute = AppCashflowRouteImport.update({
  id: '/cashflow',
  path: '/cashflow',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppBankRoute = AppBankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alerts': typeof AppAlertsRoute
  '/bank': typeof AppBankRoute
  '/calendar': typeof AppCalendarRoute
  '/cashflow': typeof AppCashflowRoute
  '/clients': typeof AppClientsRoute
  '/commissions': typeof AppCommissionsRoute
  '/contracts': typeof AppContractsRoute
  '/credit-intelligence': typeof AppCreditIntelligenceRoute
  '/dashboard': typeof AppDashboardRoute
  '/financial': typeof AppFinancialRoute
  '/forecast': typeof AppForecastRoute
  '/goals': typeof AppGoalsRoute
  '/insights': typeof AppInsightsRoute
  '/investments': typeof AppInvestmentsRoute
  '/ranking': typeof AppRankingRoute
  '/reports': typeof AppReportsRoute
  '/sales': typeof AppSalesRoute
  '/services': typeof AppServicesRoute
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
  '/sign/$token': typeof SignTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alerts': typeof AppAlertsRoute
  '/bank': typeof AppBankRoute
  '/calendar': typeof AppCalendarRoute
  '/cashflow': typeof AppCashflowRoute
  '/clients': typeof AppClientsRoute
  '/commissions': typeof AppCommissionsRoute
  '/contracts': typeof AppContractsRoute
  '/credit-intelligence': typeof AppCreditIntelligenceRoute
  '/dashboard': typeof AppDashboardRoute
  '/financial': typeof AppFinancialRoute
  '/forecast': typeof AppForecastRoute
  '/goals': typeof AppGoalsRoute
  '/insights': typeof AppInsightsRoute
  '/investments': typeof AppInvestmentsRoute
  '/ranking': typeof AppRankingRoute
  '/reports': typeof AppReportsRoute
  '/sales': typeof AppSalesRoute
  '/services': typeof AppServicesRoute
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
  '/sign/$token': typeof SignTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/bank': typeof AppBankRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/cashflow': typeof AppCashflowRoute
  '/_app/clients': typeof AppClientsRoute
  '/_app/commissions': typeof AppCommissionsRoute
  '/_app/contracts': typeof AppContractsRoute
  '/_app/credit-intelligence': typeof AppCreditIntelligenceRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/financial': typeof AppFinancialRoute
  '/_app/forecast': typeof AppForecastRoute
  '/_app/goals': typeof AppGoalsRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/investments': typeof AppInvestmentsRoute
  '/_app/ranking': typeof AppRankingRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/sales': typeof AppSalesRoute
  '/_app/services': typeof AppServicesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/users': typeof AppUsersRoute
  '/sign/$token': typeof SignTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/alerts'
    | '/bank'
    | '/calendar'
    | '/cashflow'
    | '/clients'
    | '/commissions'
    | '/contracts'
    | '/credit-intelligence'
    | '/dashboard'
    | '/financial'
    | '/forecast'
    | '/goals'
    | '/insights'
    | '/investments'
    | '/ranking'
    | '/reports'
    | '/sales'
    | '/services'
    | '/settings'
    | '/users'
    | '/sign/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/alerts'
    | '/bank'
    | '/calendar'
    | '/cashflow'
    | '/clients'
    | '/commissions'
    | '/contracts'
    | '/credit-intelligence'
    | '/dashboard'
    | '/financial'
    | '/forecast'
    | '/goals'
    | '/insights'
    | '/investments'
    | '/ranking'
    | '/reports'
    | '/sales'
    | '/services'
    | '/settings'
    | '/users'
    | '/sign/$token'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/alerts'
    | '/_app/bank'
    | '/_app/calendar'
    | '/_app/cashflow'
    | '/_app/clients'
    | '/_app/commissions'
    | '/_app/contracts'
    | '/_app/credit-intelligence'
    | '/_app/dashboard'
    | '/_app/financial'
    | '/_app/forecast'
    | '/_app/goals'
    | '/_app/insights'
    | '/_app/investments'
    | '/_app/ranking'
    | '/_app/reports'
    | '/_app/sales'
    | '/_app/services'
    | '/_app/settings'
    | '/_app/users'
    | '/sign/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignTokenRoute: typeof SignTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign/$token': {
      id: '/sign/$token'
      path: '/sign/$token'
      fullPath: '/sign/$token'
      preLoaderRoute: typeof SignTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services': {
      id: '/_app/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ranking': {
      id: '/_app/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AppRankingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/investments': {
      id: '/_app/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof AppInvestmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goals': {
      id: '/_app/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forecast': {
      id: '/_app/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof AppForecastRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financial': {
      id: '/_app/financial'
      path: '/financial'
      fullPath: '/financial'
      preLoaderRoute: typeof AppFinancialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/credit-intelligence': {
      id: '/_app/credit-intelligence'
      path: '/credit-intelligence'
      fullPath: '/credit-intelligence'
      preLoaderRoute: typeof AppCreditIntelligenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts': {
      id: '/_app/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof AppContractsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/commissions': {
      id: '/_app/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof AppCommissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cashflow': {
      id: '/_app/cashflow'
      path: '/cashflow'
      fullPath: '/cashflow'
      preLoaderRoute: typeof AppCashflowRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bank': {
      id: '/_app/bank'
      path: '/bank'
      fullPath: '/bank'
      preLoaderRoute: typeof AppBankRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppBankRoute: typeof AppBankRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppCashflowRoute: typeof AppCashflowRoute
  AppClientsRoute: typeof AppClientsRoute
  AppCommissionsRoute: typeof AppCommissionsRoute
  AppContractsRoute: typeof AppContractsRoute
  AppCreditIntelligenceRoute: typeof AppCreditIntelligenceRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFinancialRoute: typeof AppFinancialRoute
  AppForecastRoute: typeof AppForecastRoute
  AppGoalsRoute: typeof AppGoalsRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppInvestmentsRoute: typeof AppInvestmentsRoute
  AppRankingRoute: typeof AppRankingRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSalesRoute: typeof AppSalesRoute
  AppServicesRoute: typeof AppServicesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsersRoute: typeof AppUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppBankRoute: AppBankRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppCashflowRoute: AppCashflowRoute,
  AppClientsRoute: AppClientsRoute,
  AppCommissionsRoute: AppCommissionsRoute,
  AppContractsRoute: AppContractsRoute,
  AppCreditIntelligenceRoute: AppCreditIntelligenceRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFinancialRoute: AppFinancialRoute,
  AppForecastRoute: AppForecastRoute,
  AppGoalsRoute: AppGoalsRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppInvestmentsRoute: AppInvestmentsRoute,
  AppRankingRoute: AppRankingRoute,
  AppReportsRoute: AppReportsRoute,
  AppSalesRoute: AppSalesRoute,
  AppServicesRoute: AppServicesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUsersRoute: AppUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignTokenRoute: SignTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
